---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  namespace: stg
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: connect-web
    spec:
      containers:
      - name: web
        image: docker_image
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        command:
        - "/bin/bash"
        - "-c"
        - bundle exec rake assets:precompile && bundle exec puma -C ./config/puma.rb
        env:
        - name: TZ
          value: EST
        - name: REST_API_ID
          value: 1234abcd
        - name: USE_SSL
          value: true
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: test-joyous-peak
              key: database-url
        - name: PII_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: test-joyous-peak
              key: pii-encryption-key
