apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: <%= id %>
spec:
  replicas: <%= replica_count %>
  template:
    metadata:
      labels:
        app: example-<%= id %>
    spec:
      containers:
        - name: <%= id %>
          image: organization/project:<%= image_tag %>
          imagePullPolicy: Always
          command: <%= command_array.to_s %>

