apiVersion: <%= api_version %>
kind: Deployment
metadata:
  name: <%= project_name %>
  namespace: <%= namespace %>
spec:
  replicas: <%= replica_count %>
  template:
    metadata:
      labels:
        app: <%= app_name %>
    spec:
      containers:
        - name: web
          image: <%= image %>:<%= image_tag %>
          imagePullPolicy: <%= image_pull_policy %>
          command: <%= command_array.to_s %>
